### ISSUE TITLE
Project for Final Fantasy Tactics Advance

### ISSUE THREAD

**Issue by SmalkiGroove** [jiangzhengwenjz/totkol#3]
Hi,

I'm using this issue to contact the creator of this disassembly project because there is no messaging in Github 😄 

Considering this game has pretty much the same engine as FFTA, do you think you can create a decomp project for this game ? I've been working on a rom hack but the tools are very limited. I have no idea about the time and effort it would require but I could try to help.

Also if you have a Discord server for those projects, or if you know by chance an already existing decomp for FFTA, please let me know.

Thanks !

**Comment by hobohyperborian** [comment]
I seriously doubt that a decompilation of TO TKOL would assist in decompiling or otherwise modding FFTA.

My TO TKOL spreadsheet editors could be used as a template to make modding tools for FFTA.

https://github.com/hobohyperborian/to-tkol-sheets

I made them because Nightmare modules are painful to use, and that's all we had prior to those spreadsheets.

From what I remember FFTA has some odd data formats. It uses a pair of array indices to determine what action skills a job gets, which makes non-duplicate jobs a nightmare to create. It also doesn't provide flags for element or debuff immunities on items, instead letting you select from hardcoded effects. It does something similar for ability effects and formulas.

If I were you I would aak the people at FFHacktics, specifically their discord. Some people find them disagreeable, YMMV; tread lightly until you have a better grasp on the culture.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by jiangzhengwenjz** [comment]
> Considering this game has pretty much the same engine as FFTA, do you think you can create a decomp project for this game? I've been working on a rom hack but the tools are very limited. I have no idea about the time and effort it would require but I could try to help.

I can create a repo for FFTA for sure, but I must warn you of the amount of time taken by finishing a decomp project. I'm currently working on a [decompilation project of Kirby & the Amazing Mirror](https://github.com/jiangzhengwenjz/katam). It's been 3.5 years and we only have 60% code decompiled. Totkol has about the same size of code (~1.4MB) as that of katam but I would expect FFTA to be a larger project.

> Also if you have a Discord server for those projects, or if you know by chance an already existing decomp for FFTA, please let me know.

I don't think there's an existing FFTA repo. I also don't have a server for this, but I'm `jiang5048` on discord.

**Comment by SmalkiGroove** [comment]
Thank you for your answers, I will continue the conversation on Discord 👍
